name: Deploy to KinD Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up KinD cluster
      - name: Set up KinD cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.20.0

      # Step 3: Configure kubectl
      - name: Configure kubectl
        run: |
          kubectl cluster-info
          kubectl get nodes

      # Step 4: Apply Kubernetes manifests
      - name: Deploy application
        run: |
          kubectl apply -f .
        

   
